# This is a basic workflow to help you get started with Actions

name: Publish package to pypi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          # The version of poetry to install
          poetry-version: 1.1.8
      
      # - name: Remove poetry cache
      #   run: poetry cache clear --all
          
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Set poetry package version
        run: poetry version ${{ env.RELEASE_VERSION }}
      
      - name: Poetry build
        run: poetry build
        
      - name: Poetry publish
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Panoply ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
  update-brew:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/update_brew_formula.yml@master
