# This is a basic workflow to help you get started with Actions

name: Publish package to brew

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install poet
        run: pip install homebrew-pypi-poet

      - name: Generate formula
        run: mkdir brew && poet -f panoply > brew/panoply.rb

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: brew
          destination-github-username: jeremynac
          destination-repository-name: homebrew-panoply
          user-email: jeremy.naccache@epitech.eu
          target-branch: main
